# Generated by Django 4.2.5 on 2023-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo3yapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
