# Generated by Django 4.2.5 on 2023-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo3yapp', '0004_remove_record_city_remove_record_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
